### ISSUE TITLE
Project: Revival of Peer Mentorship

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_team#161]
## Description

Proposed by Jerry, experienced researchers 'adopt' a junior researcher (often a referral) within their field of expertise and act as a source of information and support about SCRF's publication process and as their chosen discipline.

## Process
- [x] Identify interested junior and senior researchers
- [ ] Propose to Ops
- [ ] Consider the potential impact on the document pipeline
- [ ] Pilot project (perhaps Zero-Knowledge)
- [ ] Present to researchers 
- [ ] Phase Two
- [ ] Assess, tweaks?

**Comment by 29988122** [comment]
Status: am doing one with Bill wu (cause we pretty much known of each other).

The point is to ...formalize it?, possibly as a culture(can't enforce that, but I don't know how to encourage that, either); so that newcomers can find their trusted friends/person, make it feel approachable, and get response in a guided and fashion. 

(I guess - it's by formalizing that, ppl would look at the rules and say: oh I had no idea. Now I know it's ok asking him/her, it won't bother him/her - and it's billable, and the culture encourage it, so why not.)

It's NOT meant to be a full-on scholar tutoring, that can be done in the open discussion - it should be like "your friendly TAs that seems less intimidating than profs", to lower the mental burden and to provide mental safetyness. (a plus that you can communicate in mother tongue)
You know, asian students...

--
ofc I must emphasise that, it's also doable if we were to make it field-specific. Just to provide slightly variations of such advices.

Should be futher discussed to make it REALLY FEASIBLE - I have 0 experiences doing HR things, only some garage psychology.
Due to the nature of my ..sins? I don't know how to push this forward correctly, but I feel obliged and is able to join the discussions, if I'm needed in the discussion process.

A repeatable fashion/flow/how to generate such culture, should be discussed, from onboarding to 1stdraftproduced/2commentsproduced, for exmaple.

**Comment by eleventh19** [comment]
@29988122 It'd be great to have a breakout discussion with Deane and James and I if I can sit in (though don't let me hold it up)

**Comment by 29988122** [comment]
I'm checking Deane's time on the public calendar:
![圖片](https://user-images.githubusercontent.com/5474709/131491226-12656a56-642c-4100-816a-b68c80325baa.png)
This is UTC+8 in the pic, so 09/04 UTC+0 0001~0100.

Is this time ok to @eleventh19 you and @jamesmcgirk ?
Or you meant that we should choose another time slot.

**Comment by jamesmcgirk** [comment]
3pm on Saturday my time, so it should be pretty good

**Comment by jamesmcgirk** [comment]
Meeting with Deane postponed, let's try again this week @29988122

**Comment by 29988122** [comment]
I found out that the original time on the public calendar has been changed for AIoT mentorship; and another time slot is 3am for Taiwanese people, thus I'm unlikely to be awake at the time.

@jamesmcgirk  Would you like to ask Deane to see if there's other time slots available to him, and also doable to you? Thanks.

**Comment by jamesmcgirk** [comment]
Just sent you both an email about chatting early next week

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by 29988122** [comment]
https://github.com/smartcontractresearchforum/research_team/issues/167#issuecomment-915763854
Should we wait till we have documentation generated here? 
Or, is the target's slightly different? (a 12-ish week mentorship training sessions versus 1-to-1 pair guidance)

**Comment by jamesmcgirk** [comment]
Goal here is to see if we can merge it with Deane's workshop, so I'm hoping we can talk to him. He's finalizing the details of his project, so that should happen soon

**Comment by jamesmcgirk** [comment]
@29988122 I mentioned this in our community call, but I'll repeat it here in case anyone else is wondering: our AI, IoT, Blockchain open hours are open to all.

**Comment by 29988122** [comment]
Partial results after meeting with Deane:
I'll approach some Taiwanese SCRF members in private, to see if they're interested in a small group, or even 1-on-1 talking sessions with James/Deane. Timeslots should be in the weekends, Morning 08:00 EST, 20:00 Taipei standard time.

Deane's workshop design itself could already build confidence for new comers of SCRF already, no matter how their language ability is - researchers here are at least capable of producing a few valuable comments and digests - they're just being shy talking in front of ppl. (fear of being corrected, don't understand the reply to them, etc) The 10-ish ppl settings in the community call also makes it worse. Therefore a few English expression crash courses could potentially raise their morale and confidence, and the result being more time being spent and more output produced for SCRF.

Todos, thoughts: 
- Should it really be 1-on-1?(inefficient labour wise) Or in a 3-4 ppl small group settings?
- How do we evaluate the outcome of each session? It won't be based on their true progress(it's not gonna improve significantly with only a few sessions), but rather....on their self evaluation? Honestly I have no idea. @jamesmcgirk Some inputs would be nice.
- Should it be recurring(in a sense forcing ppl to improve, the same principle of the 9-week? workshop by Deane), or on-demand?
- The 1-on-1 session should be non-serious for ppl to build their confidence, but then without talking about researches what should be the agenda of the session?
- How to approach potential participants in SCRF. I mean I do have 3-4 SCF ppl asking me directly about how I learned my Japanese/English...but the intention of this plan is to leave no one behind. However pinging them one by one seems silly and increases unnecessary pressure... @jamesmcgirk What's your take on this? Do you have some ideas about active Taiwanese researchers but seldom participate/talk in the meetings?

etc.

**Comment by jamesmcgirk** [comment]
Let’s a have a chat about this soon! Glad you spoke to Deane, have some thoughts about getting people to participate I’ll share

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by 29988122** [comment]
Closed as it's now pivoting into this https://github.com/smartcontractresearchforum/research_team/issues/181 .
