### ISSUE TITLE
Project: Community outreach in Kaohsiung

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_team#162]
## Description

Jerry is interested in inviting speakers and running a blockchain club in Southern Taiwan, exposing their engineers to blockchain concepts and education.

## Process

- [x] Draft a one-page proposal
- [ ] Confer with ops
- [ ] Pilot project
- [ ] Assessment
- [ ] Second phase

**Comment by jamesmcgirk** [comment]
Maybe we could combine with [the following issue](https://github.com/smartcontractresearchforum/research_team/issues/162)

**Comment by 29988122** [comment]
Be advised: proper proposal won't be out recently. Just a heads up with random thoughts.

Main target: to bridge the CS resources gap between urban and remote areas.
In taipei, if you graduated from NTU/other top schools as bachelor/MS, you get anywhere from 25000 usd to 45000 usd, excluding extreme values.
Meanwhile in Kaousiung, you're lucky if you get 15000/year, no matter where you've graduated from. I'm not joking, and this is a level one municipality city in Taiwan, same as Taipei. (read: many budgets and constructions, but still...)

CS, especially Blockchain, has many remote teams(more post-covid). I am the one who benefit from it, and I want ppl in Kaousiung also benefit from it. It's not a knowledge gap, it's pure information gap. I want to fill in that gap, by NPO fundings like SCRF, and hope to make it more sustainable in the future. I'm motivated doing this in my free time, as this is what I've seen in the TEM days(pre-covid), and I wanna shift it.

Correction: it's not about setting up a club. Organizing ppl and gaining leadership is not something particularily interesting to me.

More of like, blending in currently existing univ clubs as their advisor (already received some mails from southern univs in Taiwan in the past as TEM coorganizers);
Doing classes as per club leader requested, or guide them with proper targets and syllabus.
Blend in their discord servers/line chat groups.
(in short: don't let them fall into the financial side of blockchain, especially for CS students. Influence them in every way possible. Also teaching thme the importance of reading English..)
For formal classes, I have existing connections with profs there, got one firm in NCKU, acquaintances in other univ - but should be doable, not the main hurdle here. I could also be having a 3-hour class in a 18 week class, for example - make it regular every semester, if possible. Out of class time talk/presentation is also considered.

For mid-long term, I have pocket lists for local speakers who are perfectly capable of helping organizing hackathons/running workshops( All of them are from TEM possibly, not gonna to do * benifit tunneling *). I was the co-admin of Crosslink 2019 conf https://crosslink.taipei/  (make sure you checked the speakers to know its * property *) - so this is the kind of activity that I'm comfortable with. 
This will be the only part SCRF needs to pay larger amounts for tutors/trachers. (I'll count myself normal SCRF hourly rate before doing this full-scale i.e., workshops and hackathons; should do MVP first i.e., as an advisor/tutor/presenter myself.)

Just that, in order to lure them into a 220min train round trip and possible transit traffic times, an reasonable hourly rate is to be investigated. I'm out of reach to the rate of Taiwan presentation/talk/training pricing, TBH. 

The Loooong term project would be leaving them enough materials/SOPs/protocols, so that the blockchain clubs in each univ can have sustainable cultures, and in the process maybe SCRF's hourly rate can be used to incentivize students for doing organizational works/TAs.
Another one will be giving them the right learning directions, and use the connections from TEM and SCRF, train them(in their preferred areas ofc) and introduce them to the potential recruiting projects/teams, part-time during their bachelor/ms, or full time after graduation. This is the ultimate goal as that makes them able to live in their homeland, while still able to work and make local community more thriving.

**Comment by Siemingfong** [comment]
@29988122 I think it's a great idea to bring CS courses outside of the colleges. Because lots of the course in Taiwan is focused on how to use blockchain to invest projects, it causes information gap between CS students and the citizen. It definitely really needs to host a blockchain technology lecture to eliminate the knowledge gap. We can organize the course 
all around Taiwan.

**Comment by 29988122** [comment]
Memo:
https://docs.google.com/document/d/1gfnIgkNGfg0u8RuyazvB-olIe2__2PwS0UQfsASSzPY/edit#

The *Ideas for SCRF’s alignment with the blockchain clubs* can work as an alternative method for growing undergrad/grad talents.

However, to be 100% honest - even for the best schools (top 8, we called them 四大四中); I don't think undergrad ppl in the blockchain club @ Taiwan would be able to conduct researches independently, not even with carefully guidance by myself. Main reason: Lack of English literacy (slightly exagerrated here), unfortunately. Perhaps it will change after I took over the role of club's mentor, who knows...

Well this won't happen recently, just feel the need to mention this for now.

Related ticket:
https://github.com/smartcontractresearchforum/research_team/issues/123

**Comment by jamesmcgirk** [comment]
Need resources and PMs in place...

**Comment by 29988122** [comment]
Is being activately planned, alone with:
- #111 (Scheduling APAC Outreach and Onboarding meetings)
- #123

**Comment by jamesmcgirk** [comment]
@29988122 we should start working on a project proposal -- do you have time to start this one next week?

**Comment by 29988122** [comment]
Sure, make it formal and (best effort)exhaustive, thus I can plan ahead and be ready. 
After I moved to Kaohsiung and settle down, I can start immediately and (possibly) lure students with solid foundation from univ into Deane's research workshop, it would be very fitting.

Together with this issue https://github.com/smartcontractresearchforum/research_team/issues/161 , should we arrange a quick 1 on 1 meeting to have a rough discussion about these two?

**Comment by jamesmcgirk** [comment]
Sounds good! I'll send you a note on Discord to schedule a meeting

**Comment by eleventh19** [comment]
Met with @29988122 today to discuss. He'll put together an overview of 10 hours of work on this and then will regroup

**Comment by encore9870** [comment]
Jerry has competing priorities and so does scrf in the near future. Closing this for now. Good idea though!
