### ISSUE TITLE
New Content Type: Live Tweeting a conference.

### ISSUE THREAD

**Issue by cryptohazard** [smartcontractresearchforum/research_team#57]
Engagement experiment: Financial Cryptography ‘21 Live Tweeting

My notes: https://docs.google.com/document/d/1oIxZiY7iy7QP5oLu2duNnyU735G4rQnWkJYXwM6ZDcc/edit#

**Comment by jamesmcgirk** [comment]
@cryptohazard thanks for doing this! we're thinking about turning this into a content type during Q2

**Comment by cryptohazard** [comment]
@jamesmcgirk did you draft yet  how you see us do that going forward?

**Comment by jamesmcgirk** [comment]
@cryptohazard we saw the draft, thank you for doing it. It was a good experiment and I think we'll probably incorporate something similar into our social media strategy, I think I'll close the ticket for now since we've done the project, done the draft and adapted it into one of our existing projects

**Comment by jamesmcgirk** [comment]
@cryptohazard is this one ready for content review yet?

**Comment by jamesmcgirk** [comment]
(removed a comment for cipherex that belonged on another post) 

Might be interesting to identify opportunities for live-tweeting (and retweeting other live tweeters)

**Comment by encore9870** [comment]
This ticket is no longer relevant (until perhaps Jean is more available?). Let me know if we should not be closing it!
